env:
  global:
      - REPO_DIR="pyreadstat"
      - BUILD_COMMIT=de8d32f846d8c9ed3aadd7dc3d91bdca4270d8e5
      - PLAT=x86_64
      - UNICODE_WIDTH=32
      - WHEELHOUSE_UPLOADER_USERNAME=travis-worker
      - ANACONDA_ORG=ofajardo
      - ANACONDA_ORG_TOKEN=$ANACONDA_TOKEN
      - PACKAGE_VERSION="0.2.9"

language: python
# Default Python version is usually 2.7
python: 3.5
sudo: required
dist: trusty
services: docker

matrix:
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - PLAT=i686
    - os: osx
      language: generic
      env: MB_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.8

before_install:
    - BUILD_DEPENDS="Cython pandas"
    - TEST_DEPENDS="pandas"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

after_success:
    # upload to anaconda cloud
    - cd ${TRAVIS_BUILD_DIR}/wheelhouse
    - ls -l
    #- ls ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl
    - pip install anaconda-client
      #- anaconda -t $ANACONDA_ORG_TOKEN upload --force -u $ANACONDA_ORG --package pyreadstat --version $PACKAGE_VERSION ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl
    - anaconda -t $ANACONDA_ORG_TOKEN upload --force -u $ANACONDA_ORG *.whl


