env:
  global:
    - REPO_DIR="pyreadstat"
    - BUILD_COMMIT=de8d32f846d8c9ed3aadd7dc3d91bdca4270d8e5
    - PLAT=x86_64
    - UNICODE_WIDTH=32

language: python
# Default Python version is usually 2.7
python: 3.5
dist: trusty
services: docker


