env:
  global:
    - REPO_DIR="pyreadstat"
    - BUILD_COMMIT=de8d32f846d8c9ed3aadd7dc3d91bdca4270d8e5
    - PLAT=x86_64
    - UNICODE_WIDTH=32

language: python
# Default Python version is usually 2.7
python: 3.5
dist: trusty
services: docker

matrix:
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7

before_install:
    - BUILD_DEPENDS="Cython pandas"
    - TEST_DEPENDS="pandas"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT
