env:
  global:
      - REPO_DIR="pyreadstat"
      - BUILD_COMMIT=d6ce1cc58e5ddf16927fe1d1e0d61e14dc72c37a
      - PLAT=x86_64
      - UNICODE_WIDTH=32
      - ANACONDA_ORG=ofajardo
      - ANACONDA_ORG_TOKEN=$ANACONDA_TOKEN

language: python
# Default Python version is usually 2.7
python: 3.5
sudo: required
dist: trusty
services: docker

matrix:
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - PLAT=i686
    - os: osx
      language: generic
      env: MB_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.8

before_install:
    - BUILD_DEPENDS="Cython pandas"
    - TEST_DEPENDS="pandas"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

after_success:
    # upload to anaconda cloud
    - python --version
    - ls ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl
    # install anaconda client from github as the version on pypi is too old
    - pip install git+https://github.com/Anaconda-Platform/anaconda-client
    - anaconda -t $ANACONDA_ORG_TOKEN upload --force -u $ANACONDA_ORG ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl


